---

- include: install.yml

- name: Output directory for Diffie-Hellman parameters exists
  file:
    path: "{{ dhparam_file | dirname }}"
    state: directory

- name: The Diffie-Hellman parameter file is generated
  shell: /usr/bin/openssl dhparam -out "{{ dhparam_file }}" {{ dhparam_size }}
  creates: "{{ dhparam_file }}"

- include: cron.yml
