---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: molecule/default/yaml-lint.yml
platforms:
  - name: debian8
    image: debian:8
  - name: debian9
    image: debian:9
  - name: ubuntu-16.04
    image: ubuntu:16.04
  - name: ubuntu-18.04
    image: ubuntu:18.04
  - name: centos7
    image: centos:7
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      x: ["403"]
verifier:
  name: testinfra
  lint:
    name: flake8
